# Generated by Django 4.2.3 on 2023-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('articles', '0002_articles_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='tags.tag'),
        ),
    ]
