# Generated by Django 4.2.3 on 2023-08-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
