# Generated by Django 4.2.3 on 2023-08-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_num_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='num_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
