# Generated by Django 3.2 on 2023-08-21 07:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=100, populate_from='title', unique=True),
        ),
    ]
