# Generated by Django 3.2 on 2023-08-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20230821_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
