# Generated by Django 4.2.3 on 2023-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_id',
            field=models.IntegerField(null=True),
        ),
    ]
