# Generated by Django 4.2.3 on 2023-08-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_thread_thread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_id',
        ),
    ]
