# Generated by Django 4.2.3 on 2023-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('threads', '0003_remove_thread_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='threads', to='tags.tag'),
        ),
    ]
