# Generated by Django 4.2.3 on 2023-08-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_alter_thread_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('C', 'Đang chờ'), ('P', 'Công khai'), ('B', 'Cấm')], default='C', max_length=1),
        ),
    ]
