# Generated by Django 4.2.3 on 2023-08-14 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0007_thread_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='threads_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
