# Generated by Django 4.2.3 on 2023-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_alter_thread_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='numviews',
            field=models.IntegerField(default=0),
        ),
    ]
