# Generated by Django 4.2.3 on 2023-08-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_thread_numviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='numviews',
            new_name='num_views',
        ),
    ]
