# Generated by Django 4.2.3 on 2023-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_rename_numviews_thread_num_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
