# Generated by Django 4.2.3 on 2023-08-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_thread_is_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='num_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
