# Generated by Django 3.2 on 2023-08-22 02:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_alter_thread_num_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=100, populate_from='title', unique=True),
        ),
    ]
