# Generated by Django 4.2.3 on 2023-08-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images'),
        ),
    ]
