# Generated by Django 4.2.4 on 2023-09-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='other_name',
            field=models.CharField(blank=True, default='Đang cập nhật', max_length=500, null=True, verbose_name='Tên khác'),
        ),
    ]
