# Generated by Django 4.2.4 on 2023-09-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_topic_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, default='streamline:interface-edit-pin-2-pin-push-thumbtack', max_length=50, null=True, verbose_name='Icon'),
        ),
    ]
