# Generated by Django 4.2.3 on 2023-08-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_num_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='num_comments',
        ),
    ]
