# Generated by Django 4.2.3 on 2023-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Category'),
        ),
    ]
