# Generated by Django 4.2.3 on 2023-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0003_category_num_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
