# Generated by Django 4.2.3 on 2023-08-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0004_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='cover',
        ),
    ]
