# Generated by Django 4.2.4 on 2023-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0005_rename_image_category_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Danh mục'),
        ),
    ]
