# Generated by Django 4.2.4 on 2023-08-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0006_category_name_vi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_vi',
            field=models.CharField(blank=True, default='Đang cập nhật', max_length=500, null=True, verbose_name='Danh mục'),
        ),
    ]
