# Generated by Django 4.2.4 on 2023-09-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0008_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_vi',
            field=models.CharField(blank=True, default='Đang cập nhật', max_length=500, null=True, verbose_name='Tên khác'),
        ),
    ]
