# Generated by Django 4.2.4 on 2023-09-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0010_rename_name_vi_category_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='streamline:interface-edit-pin-2-pin-push-thumbtack', max_length=50, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='other_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Tên khác'),
        ),
    ]
