# Generated by Django 4.2.3 on 2023-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
